### PR TITLE
Update nuxt to v1.2

### PR DESCRIPTION
**Pull request by njam**
Related to https://github.com/njam/nuxt-i18n-module/pull/3

It seems to work fine for both `nuxt build` and `nuxt dev`, but maybe I'm missing something.
wdyt?

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
For me the generation doesn't work `npm run generate` (Was testing with the module directly included via package). I got
screen shot 2018-01-29 at 12 48 52
But files are not generated. 
And yes. `nuxt build` and `nuxt dev` work - in these cases it doesn't depend on the files in the `dist` folder.

**Comment by njam** [comment]
You're right. Now?

**Comment by christopheschwyzer** [comment]
Cool cool. Thanks!!!

**Comment by christopheschwyzer** [comment]
This became obsolete with https://github.com/MadeInBasel/madeinbasel-website/pull/43 (updated and used the module)

**Pull request closed without merging**
