### PR TITLE
Always include language in URLs

### PR DESCRIPTION
**Pull request by njam**
Der erste Teil.
Bitte gut testen!

### CODE REVIEW

**Comment by njam** [comment]
Vielleicht wärs auch cool für ein Projekt mit so wenigen Routen sprachspezifische Aliase zu verwenden, z.b.:
/members
/mitglieder
etc

**Comment by christopheschwyzer** [comment]
Not sure the last commit makes sense as it is. Default "/" route wouldn't work otherwise? Unfortunately we can't put the code into middleware as it doesn't get executed on first load (server).

**Comment by njam** [comment]
I'm experiencing some problems with the spinner on the index page.
When investigating I noticed that the spinner is not very useful currently, because it will only be displayed between when the application is fully loaded from the network until it is initialized in the browser.

This is a filmstrip with 8Mb/s network throttling. Loading the page takes ~8 seconds (!)
image

The spinner is only visible for a few milliseconds.
I will remove the spinner for now. I think we should rather try to reduce the download size. Let me know if you disagree.

**Comment by christopheschwyzer** [comment]
makes sense. And yes "~8 seconds " is way too much. I will investigate it in a separate issue.

**Comment by njam** [comment]
Oh wollte gar noch nicht pushen. Jetzt ist aber glaub alles fertig, die Funktionalität sollte wieder die gleiche sein.
Die Idee war, alles zum Thema i18n in ein Modul zu verschieben. Vielleicht kann man es später sogar in ein eigenes Repo verlegen.

Könntest du nochmals testen?

**Comment by christopheschwyzer** [comment]
Separates Modul ftw!
lgtm

**Comment by christopheschwyzer** [comment]
I will merge it! Thanks

**Pull request merged**
